name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Cache Cypress binary
      - name: Cache Cypress binary
        uses: actions/cache@v3
        id: cypress-cache
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Install Cypress binary (if not cached)
      - name: Install Cypress binary
        run: npx cypress install

      # Step 6: Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run